"use client";

import {useState} from "react";
import {createClient} from "@/utils/supabase/client";

type Item={experience_id:string;title:string;description:string|null;status:string;visibility:string;latitude:number|null;longitude:number|null};
type Props={item:Item;onBack:()=>void;onEdit:()=>void;onDeleted:()=>void};

export default function MemorialOwnerDetail({item,onBack,onEdit,onDeleted}:Props){
 const supabase=createClient();
 const[confirming,setConfirming]=useState(false);const[confirmation,setConfirmation]=useState('');const[deleting,setDeleting]=useState(false);const[error,setError]=useState<string|null>(null);
 async function remove(){if(confirmation!=='DELETE')return;setDeleting(true);setError(null);const{error:deleteError}=await supabase.rpc('delete_memorial_experience',{p_experience_id:item.experience_id,p_confirmation:confirmation});setDeleting(false);if(deleteError){setError(deleteError.message);return}onDeleted()}
 return <div className="flex h-full min-h-0 flex-col bg-white"><div className="flex items-center gap-3 border-b border-night-sky/10 px-5 py-4"><button onClick={onBack} className="flex h-9 w-9 items-center justify-center rounded-full border border-night-sky/10 text-xl">←</button><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal">My Treasure</p><p className="text-sm font-semibold text-night-sky/60">Memorial</p></div></div><div className="min-h-0 flex-1 overflow-y-auto px-5 py-5"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-teal"><img src="/images/memorial-marker.svg" alt="" className="h-8 w-8"/></div><h2 className="mt-4 text-2xl font-bold text-night-sky">{item.title}</h2>{item.description&&<p className="mt-3 text-sm leading-6 text-night-sky/65">{item.description}</p>}<div className="mt-5 rounded-2xl bg-sand p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-night-sky/45">Status</p><p className="mt-1 font-bold capitalize text-night-sky">{item.status.replaceAll('_',' ')} · {item.visibility}</p>{item.latitude!=null&&item.longitude!=null&&<p className="mt-2 text-xs text-night-sky/45">{item.latitude.toFixed(6)}, {item.longitude.toFixed(6)}</p>}</div><button onClick={onEdit} className="mt-5 w-full rounded-2xl bg-night-sky px-5 py-4 text-sm font-bold text-white">Edit Memorial</button><button onClick={()=>{setConfirming(true);setConfirmation('');setError(null)}} className="mt-3 w-full rounded-2xl border border-coral/40 px-5 py-4 text-sm font-bold text-coral">Delete Memorial</button>{confirming&&<div className="mt-4 rounded-2xl border border-coral/30 bg-coral/5 p-4"><p className="text-sm font-bold text-night-sky">Delete this memorial?</p><p className="mt-2 text-xs leading-5 text-night-sky/55">This removes it from My Treasure and Trailhead and disables its NFC scan. Type <strong>DELETE</strong> in all caps to confirm.</p><input value={confirmation} onChange={e=>setConfirmation(e.target.value)} placeholder="DELETE" autoCapitalize="characters" className="mt-3 w-full rounded-xl border border-coral/30 bg-white px-3 py-3 text-sm font-bold tracking-[.15em] text-night-sky outline-none focus:border-coral"/>{error&&<p className="mt-2 text-xs font-semibold text-coral">{error}</p>}<div className="mt-3 grid grid-cols-2 gap-2"><button type="button" onClick={()=>{setConfirming(false);setConfirmation('')}} className="rounded-xl border border-night-sky/10 px-3 py-3 text-sm font-bold text-night-sky">Cancel</button><button type="button" onClick={remove} disabled={confirmation!=='DELETE'||deleting} className="rounded-xl bg-coral px-3 py-3 text-sm font-bold text-white disabled:cursor-not-allowed disabled:opacity-40">{deleting?'Deleting…':'Delete Memorial'}</button></div></div>}</div></div>
}