"use client";

import {useEffect,useState} from "react";
import {createClient} from "@/utils/supabase/client";

type Person={person_id:string;name:string;birth_date:string|null;death_date:string|null;summary:string|null;profile_photo_path:string|null};
type Detail={experience_id:string;title:string;description:string|null;memorial_story:string|null;memorial_type:string;people:Person[]};
type Props={experienceId:string;fallbackTitle:string;fallbackDescription:string|null;onBack:()=>void};

function formatDate(value:string|null){if(!value)return null;return new Date(`${value}T00:00:00`).toLocaleDateString(undefined,{month:'short',day:'numeric',year:'numeric'})}
function lifespan(person:Person){const birth=formatDate(person.birth_date),death=formatDate(person.death_date);if(birth&&death)return `${birth} — ${death}`;if(birth)return `Born ${birth}`;if(death)return `Died ${death}`;return null}
function photoUrl(path:string){if(/^https?:\/\//i.test(path))return path;return `${process.env.NEXT_PUBLIC_SUPABASE_URL}/storage/v1/object/public/profile-photos/${path.split('/').map(encodeURIComponent).join('/')}`}

export default function MemorialDiscoveryDetail({experienceId,fallbackTitle,fallbackDescription,onBack}:Props){const supabase=createClient();const[detail,setDetail]=useState<Detail|null>(null);const[loading,setLoading]=useState(true);useEffect(()=>{let alive=true;(async()=>{const{data}=await supabase.rpc('get_memorial_detail',{p_experience_id:experienceId}).maybeSingle();if(alive){setDetail((data as Detail|null)??null);setLoading(false)}})();return()=>{alive=false}},[experienceId,supabase]);const title=detail?.title||fallbackTitle;return <div className="flex h-full min-h-0 flex-col bg-white"><div className="flex items-center gap-3 border-b border-night-sky/10 px-5 py-4"><button onClick={onBack} className="flex h-9 w-9 items-center justify-center rounded-full border border-night-sky/10 text-lg">←</button><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal">Memorial</p><p className="text-sm font-semibold text-night-sky/55">Remembered on the trail</p></div></div><div className="min-h-0 flex-1 overflow-y-auto px-5 py-5"><div className="flex h-12 w-12 items-center justify-center rounded-full bg-teal"><img src="/images/memorial-marker.svg" alt="" className="h-8 w-8"/></div><h2 className="mt-4 text-2xl font-bold leading-tight text-night-sky">{title}</h2>{loading&&<p className="mt-5 text-sm text-night-sky/45">Gathering their story…</p>}{detail?.people?.length?<section className="mt-6 space-y-5">{detail.people.map(person=><article key={person.person_id} className="rounded-2xl border border-night-sky/10 bg-white p-4 shadow-sm"><div className="flex items-start gap-4">{person.profile_photo_path?<img src={photoUrl(person.profile_photo_path)} alt={person.name} className="h-20 w-20 shrink-0 rounded-2xl object-cover"/>:<div className="flex h-20 w-20 shrink-0 items-center justify-center rounded-2xl bg-sand text-2xl font-bold text-night-sky/30">{person.name.charAt(0)}</div>}<div className="min-w-0 pt-1"><h3 className="text-lg font-bold leading-tight text-night-sky">{person.name}</h3>{lifespan(person)&&<p className="mt-1 text-xs font-semibold text-night-sky/45">{lifespan(person)}</p>}</div></div>{person.summary&&<p className="mt-4 text-sm leading-6 text-night-sky/65">{person.summary}</p>}</article>)}</section>:!loading&&fallbackDescription&&<p className="mt-5 text-sm leading-6 text-night-sky/65">{fallbackDescription}</p>}{detail?.memorial_story&&<section className="mt-6 border-t border-night-sky/10 pt-5"><p className="text-xs font-bold uppercase tracking-[.16em] text-teal">About this memorial</p><p className="mt-3 whitespace-pre-line text-sm leading-7 text-night-sky/65">{detail.memorial_story}</p></section>}</div></div>}
