"use client";

import {FormEvent,useState} from "react";
import {createClient} from "@/utils/supabase/client";

type Props={onCancel:()=>void;onCreated:()=>void};
type PersonResult={person_id:string;linked_user_id:string|null;display_name:string;first_name:string;last_name:string|null;birth_date:string|null;death_date:string|null;profile_summary:string|null;bio:string|null;profile_photo_path:string|null};
const TYPES=[['headstone','Headstone'],['memorial','Memorial'],['monument','Monument'],['historic_site','Historic Site'],['event','Event']] as const;

export default function MemorialCreateForm({onCancel,onCreated}:Props){
 const supabase=createClient();
 const[title,setTitle]=useState('');const[type,setType]=useState('headstone');const[description,setDescription]=useState('');const[biography,setBiography]=useState('');const[latitude,setLatitude]=useState('');const[longitude,setLongitude]=useState('');const[visibility,setVisibility]=useState<'public'|'hidden'>('public');const[saving,setSaving]=useState(false);const[error,setError]=useState<string|null>(null);
 const[personQuery,setPersonQuery]=useState('');const[birthDate,setBirthDate]=useState('');const[searching,setSearching]=useState(false);const[results,setResults]=useState<PersonResult[]>([]);const[selected,setSelected]=useState<PersonResult[]>([]);
 async function searchPeople(){setError(null);setSearching(true);const{data,error:searchError}=await supabase.rpc('search_my_family_people',{p_query:personQuery.trim()||null,p_birth_date:birthDate||null,p_limit:20});setSearching(false);if(searchError){setError(searchError.message);return}setResults((data??[]) as PersonResult[])}
 function togglePerson(person:PersonResult){const alreadySelected=selected.some(p=>p.person_id===person.person_id);if(alreadySelected){setSelected(current=>current.filter(p=>p.person_id!==person.person_id));return}setSelected(current=>[...current,person]);setPersonQuery('');setBirthDate('');setResults([])}
 function dynamicName(){return selected.map(p=>p.display_name).join(' & ')}
 async function submit(e:FormEvent){e.preventDefault();setError(null);const lat=Number(latitude),lng=Number(longitude);const fallbackTitle=title.trim()||dynamicName();if(!fallbackTitle){setError('Add at least one family profile or give this memorial a title.');return}if(!Number.isFinite(lat)||lat<-90||lat>90||!Number.isFinite(lng)||lng<-180||lng>180){setError('Enter valid latitude and longitude coordinates.');return}setSaving(true);const{data:experienceId,error:rpcError}=await supabase.rpc('create_memorial_experience',{p_title:fallbackTitle,p_description:description.trim()||null,p_memorial_type:type,p_subject_name:dynamicName()||fallbackTitle,p_biography:biography.trim()||null,p_latitude:lat,p_longitude:lng,p_visibility:visibility,p_publish:true});if(rpcError){setSaving(false);setError(rpcError.message);return}if(selected.length&&experienceId){const{error:linkError}=await supabase.rpc('set_memorial_people',{p_experience_id:experienceId,p_person_ids:selected.map(p=>p.person_id)});if(linkError){setSaving(false);setError(`The memorial was created, but the family profiles could not be linked: ${linkError.message}`);return}}setSaving(false);onCreated()}
 const field='mt-2 w-full rounded-2xl border border-night-sky/15 bg-white px-4 py-3 text-sm text-night-sky outline-none focus:border-teal';
 return <div className="flex h-full min-h-0 flex-col bg-white"><div className="flex items-center gap-3 border-b border-night-sky/10 px-5 py-4"><button onClick={onCancel} className="flex h-9 w-9 items-center justify-center rounded-full border border-night-sky/10 text-xl">←</button><div><p className="text-xs font-bold uppercase tracking-[.18em] text-teal">My Treasure</p><h2 className="font-bold text-night-sky">Memorial / Headstone</h2></div></div><form onSubmit={submit} className="min-h-0 flex-1 overflow-y-auto px-5 py-5"><p className="text-sm leading-6 text-night-sky/60">Create a place where Trailblazers can discover the people, life, or story remembered here.</p>
 <section className="mt-5 rounded-2xl border border-night-sky/10 p-4"><div className="flex items-start justify-between gap-3"><div><p className="text-xs font-bold uppercase tracking-[.12em] text-teal">Family tree profiles</p><h3 className="mt-1 font-bold text-night-sky">Who is remembered here?</h3></div><span className="text-xs text-night-sky/40">Optional</span></div><p className="mt-2 text-xs leading-5 text-night-sky/50">Link one or more people from your LegacyLink family tree. Trailhead will use their current profile names and profile summary or bio dynamically.</p>
 {selected.length>0&&<div className="mt-3 space-y-2">{selected.map(person=><div key={person.person_id} className="flex items-center justify-between rounded-xl bg-teal/10 px-3 py-2"><div><p className="text-sm font-bold text-night-sky">{person.display_name}</p><p className="text-xs text-night-sky/45">{person.birth_date||'Birth date unknown'}{person.death_date?` – ${person.death_date}`:''}</p></div><button type="button" onClick={()=>togglePerson(person)} className="text-xs font-bold text-coral">Remove</button></div>)}<div className="rounded-xl border border-dashed border-teal/40 px-3 py-2"><p className="text-xs font-semibold text-night-sky/55">Need to add another person? Search again below. The search fields have been cleared for the next profile.</p></div></div>}
 <div className="mt-4 grid gap-2"><input value={personQuery} onChange={e=>setPersonQuery(e.target.value)} placeholder={selected.length?'Search for another person':'Search by name, Person ID, or linked User ID'} className={field}/><div className="grid grid-cols-[1fr_auto] gap-2"><input type="date" value={birthDate} onChange={e=>setBirthDate(e.target.value)} className={field}/><button type="button" onClick={searchPeople} disabled={searching} className="mt-2 rounded-2xl bg-night-sky px-4 text-sm font-bold text-white disabled:opacity-50">{searching?'Searching…':'Search'}</button></div></div>
 {results.length>0&&<div className="mt-3 max-h-48 overflow-y-auto rounded-xl border border-night-sky/10">{results.map(person=>{const chosen=selected.some(p=>p.person_id===person.person_id);return <button key={person.person_id} type="button" onClick={()=>togglePerson(person)} className={`flex w-full items-center justify-between border-b border-night-sky/5 px-3 py-3 text-left last:border-0 ${chosen?'bg-teal/10':'bg-white'}`}><div><p className="text-sm font-bold text-night-sky">{person.display_name}</p><p className="text-xs text-night-sky/45">{person.birth_date||'Birth date unknown'}{person.death_date?` – ${person.death_date}`:''}</p></div><span className="text-xs font-bold text-teal">{chosen?'Added':'Add'}</span></button>})}</div>}
 </section>
 <label className="mt-5 block text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">Memorial type<select value={type} onChange={e=>setType(e.target.value)} className={field}>{TYPES.map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></label>
 <label className="mt-4 block text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">Manual title <span className="normal-case tracking-normal text-night-sky/35">only used when no family profiles are linked</span><input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Name this memorial" className={field}/></label>
 {selected.length>0&&<div className="mt-4 rounded-2xl bg-sand p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-night-sky/45">Trailhead title preview</p><p className="mt-1 font-bold text-night-sky">{dynamicName()}</p><p className="mt-2 text-xs leading-5 text-night-sky/45">If a linked family-tree name changes later, this Trailhead title changes with it.</p></div>}
 <label className="mt-4 block text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">Manual short description <span className="normal-case tracking-normal text-night-sky/35">fallback when profiles have no summary or bio</span><textarea value={description} onChange={e=>setDescription(e.target.value)} rows={3} placeholder="A short introduction for this memorial." className={field}/></label>
 <label className="mt-4 block text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">Memorial-specific bio or story <span className="normal-case tracking-normal text-night-sky/35">optional</span><textarea value={biography} onChange={e=>setBiography(e.target.value)} rows={5} placeholder="Add context that belongs specifically to this memorial, headstone, place, or shared story." className={field}/></label>
 <div className="mt-5 rounded-2xl bg-sand p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">Location</p><p className="mt-1 text-xs leading-5 text-night-sky/45">Enter decimal GPS coordinates for the physical memorial.</p><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-xs font-semibold text-night-sky/55">Latitude<input inputMode="decimal" value={latitude} onChange={e=>setLatitude(e.target.value)} placeholder="30.688944" className={field}/></label><label className="text-xs font-semibold text-night-sky/55">Longitude<input inputMode="decimal" value={longitude} onChange={e=>setLongitude(e.target.value)} placeholder="-94.158417" className={field}/></label></div></div>
 <div className="mt-5"><p className="text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">Trailhead visibility</p><div className="mt-2 grid grid-cols-2 gap-2"><button type="button" onClick={()=>setVisibility('public')} className={`rounded-2xl border p-3 text-sm font-bold ${visibility==='public'?'border-teal bg-teal/10 text-night-sky':'border-night-sky/10 text-night-sky/50'}`}>Public</button><button type="button" onClick={()=>setVisibility('hidden')} className={`rounded-2xl border p-3 text-sm font-bold ${visibility==='hidden'?'border-teal bg-teal/10 text-night-sky':'border-night-sky/10 text-night-sky/50'}`}>Hidden</button></div><p className="mt-2 text-xs leading-5 text-night-sky/45">Public memorials appear on Trailhead. Hidden memorials remain in My Treasure until you publish them.</p></div>
 {error&&<div className="mt-5 rounded-2xl bg-coral/10 p-3 text-sm font-semibold text-night-sky">{error}</div>}<button disabled={saving} className="mt-6 w-full rounded-2xl bg-night-sky px-5 py-4 text-sm font-bold text-white disabled:opacity-50">{saving?'Adding memorial…':'Publish Memorial'}</button></form></div>
}