export const TREASURE_BOX_ADVANCED_EXPERIENCES_ENABLED =
  process.env.NEXT_PUBLIC_ENABLE_TREASURE_BOX_EXPERIENCES === "true";

export const TRAVELING_TOKEN_ADMIN_ENABLED =
  process.env.NEXT_PUBLIC_ENABLE_TRAVELING_TOKENS === "true";
