"use client";

import {useEffect,useMemo,useRef,useState} from "react";

type ReaderChapter={title:string;body:string;imageUrl?:string|null;imageAlt?:string|null};
type StoryReaderProps={title:string;summary:string;chapters:ReaderChapter[];onClose:()=>void};
type Theme="paper"|"sepia"|"night";
type Page={chapterIndex:number;chapterTitle:string;paragraphs:string[];startsChapter:boolean;imageUrl:string|null;imageAlt:string|null};
const themeClasses:Record<Theme,{shell:string;text:string;muted:string;line:string;button:string}>={paper:{shell:"bg-[#fbfaf7]",text:"text-[#20201d]",muted:"text-[#20201d]/45",line:"bg-[#20201d]/12",button:"border-[#20201d]/15 bg-white/70 text-[#20201d]"},sepia:{shell:"bg-[#f3ead7]",text:"text-[#382f25]",muted:"text-[#382f25]/45",line:"bg-[#382f25]/14",button:"border-[#382f25]/15 bg-[#f8f0df]/80 text-[#382f25]"},night:{shell:"bg-[#17191c]",text:"text-[#ece9e2]",muted:"text-[#ece9e2]/45",line:"bg-white/12",button:"border-white/15 bg-white/5 text-[#ece9e2]"}};

function splitByWords(text:string,maxChars:number){const words=text.split(/\s+/).filter(Boolean);const chunks:string[]=[];let current="";for(const word of words){const next=current?`${current} ${word}`:word;if(current&&next.length>maxChars){chunks.push(current);current=word}else current=next}if(current)chunks.push(current);return chunks}
function paginate(chapters:ReaderChapter[],capacity:number){const pages:Page[]=[];chapters.forEach((chapter,chapterIndex)=>{const raw=chapter.body.split(/\n\s*\n/).map(p=>p.replace(/\s*\n\s*/g," ").trim()).filter(Boolean);let first=true;let current:string[]=[];let used=0;const available=()=>Math.max(260,capacity-(first?280+(chapter.imageUrl?Math.floor(capacity*.42):0):0));const push=()=>{if(!current.length)return;pages.push({chapterIndex,chapterTitle:chapter.title,paragraphs:current,startsChapter:first,imageUrl:first?(chapter.imageUrl??null):null,imageAlt:first?(chapter.imageAlt??null):null});first=false;current=[];used=0};for(const paragraph of raw){const chunks=splitByWords(paragraph,Math.max(220,Math.floor(available()*.96)));for(const chunk of chunks){const cost=chunk.length+24;if(current.length&&used+cost>available())push();current.push(chunk);used+=cost}}push()});return pages}
function Chevron({direction}:{direction:"left"|"right"}){return <svg viewBox="0 0 24 24" className="h-5 w-5" fill="none" stroke="currentColor" strokeWidth="1.8" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={direction==="left"?"m15 18-6-6 6-6":"m9 18 6-6-6-6"}/></svg>}
function ChapterImage({src,alt}:{src:string;alt:string}){return <div className="relative mb-6 aspect-video w-full overflow-hidden rounded-2xl bg-black/80 shadow-sm sm:mb-7"><img src={src} alt="" aria-hidden="true" className="absolute inset-0 h-full w-full scale-110 object-cover blur-2xl opacity-55"/><div className="absolute inset-0 bg-black/20"/><img src={src} alt={alt} className="relative z-10 h-full w-full object-contain"/></div>}

export default function StoryReader({title,summary,chapters,onClose}:StoryReaderProps){const[fontSize,setFontSize]=useState(18);const[theme,setTheme]=useState<Theme>("paper");const[showType,setShowType]=useState(false);const[pageIndex,setPageIndex]=useState(-1);const[viewport,setViewport]=useState({width:390,height:700});const touchStart=useRef<number|null>(null);const pageScrollRef=useRef<HTMLDivElement|null>(null);const classes=themeClasses[theme];
 useEffect(()=>{const update=()=>{const vv=window.visualViewport;setViewport({width:vv?.width??window.innerWidth,height:vv?.height??window.innerHeight})};update();window.addEventListener("resize",update);window.visualViewport?.addEventListener("resize",update);const previous=document.body.style.overflow;document.body.style.overflow="hidden";return()=>{window.removeEventListener("resize",update);window.visualViewport?.removeEventListener("resize",update);document.body.style.overflow=previous}},[]);
 const capacity=useMemo(()=>{const horizontal=viewport.width<640?64:viewport.width<1024?150:320;const vertical=viewport.width<640?120:118;const usableWidth=Math.min(760,viewport.width-horizontal);const usableHeight=Math.max(300,viewport.height-vertical);const charsPerLine=Math.max(26,usableWidth/(fontSize*.54));const lines=usableHeight/(fontSize*1.68);return Math.max(560,Math.floor(charsPerLine*lines*1.10))},[viewport,fontSize]);
 const pages=useMemo(()=>paginate(chapters,capacity),[chapters,capacity]);useEffect(()=>{setPageIndex(current=>Math.min(current,pages.length-1))},[pages.length]);useEffect(()=>{pageScrollRef.current?.scrollTo({top:0,left:0,behavior:"auto"})},[pageIndex,fontSize]);const readingPage=pageIndex>=0?pages[pageIndex]:null;const progress=pageIndex<0?0:((pageIndex+1)/Math.max(1,pages.length))*100;
 function previous(){setShowType(false);setPageIndex(p=>Math.max(-1,p-1))}function next(){setShowType(false);setPageIndex(p=>Math.min(pages.length-1,p+1))}
 useEffect(()=>{const key=(event:KeyboardEvent)=>{if(event.key==="ArrowLeft")previous();if(event.key==="ArrowRight"||event.key===" "){event.preventDefault();next()}if(event.key==="Escape")onClose()};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[pages.length,onClose]);
 function endSwipe(x:number){if(touchStart.current===null)return;const delta=x-touchStart.current;touchStart.current=null;if(Math.abs(delta)<45)return;if(delta<0)next();else previous()}const chapterNumber=readingPage?readingPage.chapterIndex+1:0;
 return <div className={`fixed inset-0 z-[100] h-[100dvh] overflow-hidden ${classes.shell} ${classes.text}`} role="dialog" aria-modal="true" aria-label={`Reading ${title}`}><div className="flex h-full min-h-0 flex-col"><header className="relative z-20 flex h-14 shrink-0 items-center justify-between px-4 sm:h-16 sm:px-7"><button type="button" onClick={onClose} className={`inline-flex h-9 items-center gap-1 rounded-full border px-3 text-sm font-semibold backdrop-blur ${classes.button}`} aria-label="Close reader"><Chevron direction="left"/><span className="hidden sm:inline">Treasure Box</span></button><div className="pointer-events-none absolute left-1/2 max-w-[46vw] -translate-x-1/2 text-center"><p className="truncate text-[13px] font-semibold tracking-[.01em]">{title}</p>{readingPage&&<p className={`mt-0.5 text-[10px] ${classes.muted}`}>Chapter {chapterNumber}</p>}</div><div className="relative"><button type="button" onClick={()=>setShowType(v=>!v)} className={`flex h-9 min-w-9 items-center justify-center rounded-full border px-3 font-serif text-[17px] font-semibold backdrop-blur ${classes.button}`} aria-label="Reading appearance">Aa</button>{showType&&<div className={`absolute right-0 top-11 w-72 rounded-2xl border p-4 shadow-xl ${theme==="night"?"border-white/10 bg-[#25272b]":"border-black/10 bg-white"}`}><div className="flex items-center justify-between"><p className={`text-[11px] font-bold uppercase tracking-[.14em] ${classes.muted}`}>Text size</p><p className={`text-xs tabular-nums ${classes.muted}`}>{fontSize}px</p></div><div className="mt-4 flex items-center gap-3"><span className="font-serif text-sm">A</span><input type="range" min="15" max="26" step="1" value={fontSize} onChange={e=>setFontSize(Number(e.target.value))} className="h-2 flex-1 cursor-pointer accent-teal" aria-label="Text size"/><span className="font-serif text-2xl">A</span></div><p className={`mt-5 text-[11px] font-bold uppercase tracking-[.14em] ${classes.muted}`}>Appearance</p><div className="mt-3 grid grid-cols-3 gap-2"><button type="button" onClick={()=>setTheme("paper")} className={`h-10 rounded-xl border border-black/10 bg-[#fbfaf7] ${theme==="paper"?"ring-2 ring-teal ring-offset-2":""}`} aria-label="Paper theme"/><button type="button" onClick={()=>setTheme("sepia")} className={`h-10 rounded-xl border border-black/10 bg-[#f3ead7] ${theme==="sepia"?"ring-2 ring-teal ring-offset-2":""}`} aria-label="Sepia theme"/><button type="button" onClick={()=>setTheme("night")} className={`h-10 rounded-xl border border-white/20 bg-[#17191c] ${theme==="night"?"ring-2 ring-teal ring-offset-2":""}`} aria-label="Night theme"/></div></div>}</div></header>
 <main className="relative min-h-0 flex-1 overflow-hidden" onTouchStart={e=>{touchStart.current=e.touches[0]?.clientX??null}} onTouchEnd={e=>endSwipe(e.changedTouches[0]?.clientX??0)}>{pageIndex===-1?<div className="flex h-full min-h-0 items-center justify-center overflow-hidden px-6 py-2 sm:px-12 sm:py-3"><div className="flex max-h-full w-full max-w-2xl flex-col items-center justify-center text-center"><p className={`shrink-0 text-[10px] font-bold uppercase tracking-[.22em] ${classes.muted}`}>A Legacy Link Story</p><h1 className="mt-[clamp(.6rem,2vh,1.4rem)] max-w-[18ch] shrink-0 font-serif text-[clamp(2rem,min(7vw,7vh),4.6rem)] font-semibold leading-[.96] tracking-[-.035em]">{title}</h1><div className={`my-[clamp(.6rem,2vh,1.4rem)] h-px w-12 shrink-0 ${classes.line}`}/>{summary&&<p className={`max-w-xl overflow-hidden font-serif text-[clamp(.82rem,min(1.3vw,1.8vh),1.08rem)] leading-[1.55] ${theme==="night"?"text-[#ece9e2]/68":"text-current opacity-65"}`}>{summary}</p>}<div className="mt-[clamp(.6rem,1.8vh,1.25rem)] shrink-0"><p className={`text-[11px] ${classes.muted}`}>{chapters.length} {chapters.length===1?"chapter":"chapters"}</p><button type="button" onClick={()=>setPageIndex(0)} className="mt-[clamp(.5rem,1.5vh,1rem)] inline-flex min-w-44 items-center justify-center rounded-full bg-night-sky px-6 py-3 text-sm font-bold text-white">Begin reading</button></div></div></div>:readingPage?<div className="mx-auto h-full max-w-[920px] px-7 pb-[5px] pt-3 sm:px-16 sm:pb-[5px] sm:pt-6 lg:px-20"><article className="mx-auto flex h-full max-w-[700px] flex-col"><div ref={pageScrollRef} className="min-h-0 flex-1 overflow-y-auto overscroll-contain pr-1 pb-[5px]">{readingPage.startsChapter&&<div className="mb-6 sm:mb-7"><p className={`text-[10px] font-bold uppercase tracking-[.2em] ${classes.muted}`}>Chapter {chapterNumber}</p><h2 className="mt-3 font-serif text-[clamp(1.75rem,5.5vw,2.7rem)] font-semibold leading-tight">{readingPage.chapterTitle}</h2></div>}{readingPage.imageUrl&&<ChapterImage src={readingPage.imageUrl} alt={readingPage.imageAlt||`${readingPage.chapterTitle} illustration`}/>}<div className="font-serif" style={{fontSize:`${fontSize}px`,lineHeight:1.68}}>{readingPage.paragraphs.map((paragraph,i)=><p key={i} className="mb-[.72em] indent-[1.35em] first:indent-0">{paragraph}</p>)}</div></div></article></div>:null}</main>
 <footer className="shrink-0 px-5 pb-[max(10px,env(safe-area-inset-bottom))] pt-1 sm:px-8"><div className={`mx-auto h-[2px] w-full max-w-2xl ${classes.line}`}><div className="h-full bg-teal" style={{width:`${progress}%`}}/></div><div className="mx-auto mt-1 flex max-w-2xl items-center justify-between"><button type="button" onClick={previous} disabled={pageIndex===-1} className={`inline-flex h-9 items-center gap-1 px-2 text-xs font-semibold disabled:opacity-20 ${classes.muted}`}><Chevron direction="left"/>Previous</button><p className={`text-[11px] ${classes.muted}`}>{pageIndex===-1?"Cover":`Page ${pageIndex+1} of ${pages.length}`}</p><button type="button" onClick={next} disabled={pageIndex>=pages.length-1} className={`inline-flex h-9 items-center gap-1 px-2 text-xs font-semibold disabled:opacity-20 ${classes.muted}`}>Next<Chevron direction="right"/></button></div></footer></div></div>}
