"use client";

import {useEffect,useMemo,useState} from "react";
import {createClient} from "@/utils/supabase/client";
import TreasureBoxStoryBuilder from "@/components/treasure-box/TreasureBoxStoryBuilder";

type ContentOption="digital_story"|"traveling_token"|"specialty_token"|"quest";
type Step="details"|"contents"|"story"|"traveling_token"|"specialty_token"|"quest"|"review";
type Props={token:string;boxId:string;initial:{title:string;description:string|null;difficulty:number;terrain:number;latitude:number|null;longitude:number|null;search_radius_meters:number|null}};
const OPTIONS:{id:ContentOption;title:string;description:string}[]=[{id:"digital_story",title:"Digital Story",description:"Create a story Trailblazers unlock when they physically discover this box."},{id:"traveling_token",title:"Traveling Token",description:"Send a trackable token on a journey from Treasure Box to Treasure Box."},{id:"specialty_token",title:"Specialty Token",description:"Place collectible or special-edition LegacyLink tokens inside this box."},{id:"quest",title:"Quest",description:"Make this box part of an ordered adventure where each discovery unlocks the next stop."}];
function contentOptionToStep(option:ContentOption):Step{switch(option){case "digital_story":return "story";case "traveling_token":return "traveling_token";case "specialty_token":return "specialty_token";case "quest":return "quest"}}
export default function TreasureBoxSetupForm({token,boxId,initial}:Props){
 const supabase=useMemo(()=>createClient(),[]);const[title,setTitle]=useState(initial.title==="Untitled Treasure Box"?"":initial.title);const[description,setDescription]=useState(initial.description??"");const[difficulty,setDifficulty]=useState(initial.difficulty||1);const[terrain,setTerrain]=useState(initial.terrain||1);const[latitude,setLatitude]=useState(initial.latitude?.toString()??"");const[longitude,setLongitude]=useState(initial.longitude?.toString()??"");const[radius,setRadius]=useState(initial.search_radius_meters??75);const[selected,setSelected]=useState<ContentOption[]>([]);const[step,setStep]=useState<Step>("details");const[busy,setBusy]=useState(false);const[locating,setLocating]=useState(false);const[error,setError]=useState<string|null>(null);const[message,setMessage]=useState<string|null>(null);const[optionsLoaded,setOptionsLoaded]=useState(false);
 useEffect(()=>{let active=true;(async()=>{const{data}=await supabase.rpc("get_claimed_treasure_box_content_options",{p_nfc_public_token:token});if(!active)return;const values=(Array.isArray(data)?data:[]) as ContentOption[];setSelected(values);setOptionsLoaded(true)})();return()=>{active=false}},[supabase,token]);
 const steps=useMemo<Step[]>(()=>["details","contents",...selected.map(contentOptionToStep),"review"],[selected]);const index=Math.max(0,steps.indexOf(step));
 function go(next:Step){setError(null);setMessage(null);setStep(next);window.scrollTo({top:0,behavior:"smooth"})}
 function nextStep(){const i=steps.indexOf(step);if(i>=0&&i<steps.length-1)go(steps[i+1])}
 function previous(){const i=steps.indexOf(step);if(i>0)go(steps[i-1])}
 function useLocation(){setError(null);if(!navigator.geolocation){setError("Location is not available on this device. You can enter coordinates manually.");return}setLocating(true);navigator.geolocation.getCurrentPosition(pos=>{setLatitude(pos.coords.latitude.toFixed(6));setLongitude(pos.coords.longitude.toFixed(6));setLocating(false);setMessage(`Location added${Number.isFinite(pos.coords.accuracy)?` (about ${Math.round(pos.coords.accuracy)} m accuracy)`:""}. You can adjust it manually if needed.`)},()=>{setLocating(false);setError("We couldn't get your location. Try again or enter coordinates manually.")},{enableHighAccuracy:true,timeout:12000,maximumAge:0})}
 async function saveDetails(){setError(null);const lat=Number(latitude),lng=Number(longitude);if(!title.trim()){setError("Give your Treasure Box a name.");return}if(!Number.isFinite(lat)||!Number.isFinite(lng)){setError("Add the Treasure Box location before continuing.");return}setBusy(true);const{error:e}=await supabase.rpc("save_claimed_treasure_box_setup",{p_nfc_public_token:token,p_title:title.trim(),p_description:description.trim()||null,p_difficulty:difficulty,p_terrain:terrain,p_latitude:lat,p_longitude:lng,p_search_radius_meters:radius});setBusy(false);if(e){setError(e.message);return}go("contents")}
 function toggle(id:ContentOption){setSelected(current=>current.includes(id)?current.filter(x=>x!==id):[...current,id])}
 async function saveContents(){setError(null);setBusy(true);const{error:e}=await supabase.rpc("save_claimed_treasure_box_content_options",{p_nfc_public_token:token,p_content_options:selected});setBusy(false);if(e){setError(e.message);return}const dynamic:Step[]=selected.map(contentOptionToStep);go(dynamic[0]??"review")}
 const labels:Record<Step,string>={details:"Details",contents:"What's Inside",story:"Story",traveling_token:"Traveling Token",specialty_token:"Specialty Token",quest:"Quest",review:"Review"};
 const score=(label:string,value:number,setter:(v:number)=>void)=><label className="block"><span className="text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">{label}</span><select value={value} onChange={e=>setter(Number(e.target.value))} className="mt-2 w-full rounded-2xl border border-night-sky/15 bg-white px-4 py-3 text-sm">{[1,2,3,4,5].map(n=><option key={n} value={n}>{n} / 5</option>)}</select></label>;
 if(!optionsLoaded)return <div className="mt-8 rounded-2xl bg-sand p-5 text-sm font-semibold text-night-sky/60">Opening setup…</div>;
 return <div className="mt-8"><div className="mb-7"><div className="flex items-center justify-between gap-4"><p className="text-xs font-bold uppercase tracking-[.14em] text-teal">Step {index+1} of {steps.length}</p><p className="text-xs font-semibold text-night-sky/45">{labels[step]}</p></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-night-sky/10"><div className="h-full rounded-full bg-teal transition-all" style={{width:`${((index+1)/steps.length)*100}%`}}/></div><div className="mt-3 hidden gap-2 sm:flex">{steps.map((s,i)=><button key={s} type="button" onClick={()=>go(s)} className={`text-xs font-semibold ${i===index?"text-teal":"text-night-sky/40"}`}>{labels[s]}{i<steps.length-1&&<span className="ml-2 text-night-sky/20">→</span>}</button>)}</div></div>
 {step==="details"&&<section><div className="rounded-2xl bg-sand p-4"><p className="text-xs font-bold uppercase tracking-[.12em] text-night-sky/45">Physical Treasure Box</p><p className="mt-1 font-mono text-lg font-bold text-night-sky">{boxId}</p></div><h2 className="mt-6 text-2xl font-bold text-night-sky">Tell us about your Treasure Box.</h2><p className="mt-2 text-sm leading-6 text-night-sky/60">These details help Trailblazers understand the hunt before they head out.</p><div className="mt-6 space-y-5"><label className="block text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">Treasure Box name<input value={title} onChange={e=>setTitle(e.target.value)} placeholder="Give this adventure a name" className="mt-2 w-full rounded-2xl border border-night-sky/15 px-4 py-3 text-base"/></label><label className="block text-xs font-bold uppercase tracking-[.12em] text-night-sky/55">Short description<textarea value={description} onChange={e=>setDescription(e.target.value)} rows={4} placeholder="What should Trailblazers know before they start looking?" className="mt-2 w-full resize-none rounded-2xl border border-night-sky/15 px-4 py-3 text-sm leading-6"/></label><div className="grid gap-4 sm:grid-cols-2">{score("Difficulty",difficulty,setDifficulty)}{score("Terrain",terrain,setTerrain)}</div><div className="rounded-2xl border border-night-sky/10 p-4"><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><p className="text-sm font-bold">Where will you place it?</p><p className="mt-1 text-xs text-night-sky/55">Use your device at the hiding location, or enter coordinates yourself.</p></div><button type="button" onClick={useLocation} disabled={locating} className="rounded-xl bg-teal px-4 py-2.5 text-sm font-bold text-white">{locating?"Finding location…":"Use my current location"}</button></div><div className="mt-4 grid gap-3 sm:grid-cols-2"><input value={latitude} onChange={e=>setLatitude(e.target.value)} placeholder="Latitude" className="rounded-xl border border-night-sky/15 px-3 py-3 font-mono text-sm"/><input value={longitude} onChange={e=>setLongitude(e.target.value)} placeholder="Longitude" className="rounded-xl border border-night-sky/15 px-3 py-3 font-mono text-sm"/></div><select value={radius} onChange={e=>setRadius(Number(e.target.value))} className="mt-3 w-full rounded-xl border border-night-sky/15 bg-white px-3 py-3 text-sm"><option value={25}>25 meters — tight</option><option value={50}>50 meters</option><option value={75}>75 meters — standard</option><option value={100}>100 meters</option><option value={150}>150 meters — broad</option></select></div></div><WizardError error={error}/><button type="button" onClick={saveDetails} disabled={busy} className="button-primary mt-6 inline-flex w-full justify-center">{busy?"Saving…":"Save & Continue"}</button></section>}
 {step==="contents"&&<section><h2 className="text-2xl font-bold text-night-sky">What will Trailblazers discover here?</h2><p className="mt-2 text-sm leading-6 text-night-sky/60">Choose everything that belongs in this Treasure Box. Your choices determine the next setup steps.</p><div className="mt-6 grid gap-3">{OPTIONS.map(o=>{const active=selected.includes(o.id);return <button key={o.id} type="button" onClick={()=>toggle(o.id)} className={`rounded-2xl border p-4 text-left ${active?"border-teal bg-teal/10":"border-night-sky/10"}`}><span className="font-bold text-night-sky">{active?"✓ ":""}{o.title}</span><span className="mt-1 block text-sm leading-6 text-night-sky/60">{o.description}</span></button>})}</div><WizardError error={error}/><div className="mt-6 flex gap-3"><Back onClick={previous}/><button type="button" onClick={saveContents} disabled={busy} className="button-primary flex-1">{busy?"Saving…":"Save & Continue"}</button></div></section>}
 {step==="story"&&<section><TreasureBoxStoryBuilder token={token}/><div className="mt-5 flex gap-3"><Back onClick={previous}/><button type="button" onClick={nextStep} className="button-primary flex-1">Continue</button></div></section>}
 {(step==="traveling_token"||step==="specialty_token"||step==="quest")&&<section><p className="text-xs font-bold uppercase tracking-[.14em] text-teal">{labels[step]}</p><h2 className="mt-2 text-2xl font-bold text-night-sky">{labels[step]} setup comes next.</h2><p className="mt-3 leading-7 text-night-sky/60">This step is now part of the setup module and will receive its dedicated controls as we build the next feature.</p><div className="mt-6 flex gap-3"><Back onClick={previous}/><button type="button" onClick={nextStep} className="button-primary flex-1">Continue</button></div></section>}
 {step==="review"&&<section><p className="text-xs font-bold uppercase tracking-[.14em] text-teal">Review</p><h2 className="mt-2 text-2xl font-bold text-night-sky">Your setup is taking shape.</h2><p className="mt-3 leading-7 text-night-sky/60">The final review, placement confirmation, publishing and NFC verification steps will be built after the selected experience modules are complete.</p><div className="mt-6"><Back onClick={previous}/></div></section>}
 </div>}
function Back({onClick}:{onClick:()=>void}){return <button type="button" onClick={onClick} className="rounded-xl border border-night-sky/15 px-5 py-3 text-sm font-bold text-night-sky">Back</button>}
function WizardError({error}:{error:string|null}){return error?<p className="mt-4 rounded-2xl bg-coral/10 p-4 text-sm font-semibold text-night-sky">{error}</p>:null}
