create table if not exists public.admin_users (user_id uuid primary key references auth.users(id) on delete cascade,role text not null check(role in ('super_admin','admin','fulfillment')),granted_by uuid references auth.users(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
alter table public.admin_users enable row level security;
create or replace function public.is_legacy_link_admin(p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.admin_users where user_id=p_user_id and role in ('super_admin','admin','fulfillment')); $$;
create or replace function public.is_legacy_link_super_admin(p_user_id uuid default auth.uid()) returns boolean language sql stable security definer set search_path='' as $$ select exists(select 1 from public.admin_users where user_id=p_user_id and role='super_admin'); $$;
create policy "Admins can view admin users" on public.admin_users for select to authenticated using(public.is_legacy_link_admin());
create or replace function public.list_legacy_link_admins() returns table(user_id uuid,email text,role text,created_at timestamptz) language sql stable security definer set search_path='' as $$ select au.user_id,u.email::text,au.role,au.created_at from public.admin_users au join auth.users u on u.id=au.user_id where public.is_legacy_link_admin() order by au.created_at; $$;
create or replace function public.grant_legacy_link_admin(p_email text,p_role text default 'admin') returns uuid language plpgsql security definer set search_path='' as $$ declare v_user uuid; begin if not public.is_legacy_link_super_admin() then raise exception 'Super admin access required'; end if; if p_role not in ('admin','fulfillment') then raise exception 'Role must be admin or fulfillment'; end if; select id into v_user from auth.users where lower(email)=lower(trim(p_email)) limit 1; if v_user is null then raise exception 'No LegacyLink account exists for that email address'; end if; insert into public.admin_users(user_id,role,granted_by) values(v_user,p_role,auth.uid()) on conflict(user_id) do update set role=excluded.role,granted_by=auth.uid(),updated_at=now(); return v_user; end; $$;
create or replace function public.revoke_legacy_link_admin(p_user_id uuid) returns boolean language plpgsql security definer set search_path='' as $$ begin if not public.is_legacy_link_super_admin() then raise exception 'Super admin access required'; end if; if exists(select 1 from public.admin_users where user_id=p_user_id and role='super_admin') then raise exception 'Super admin cannot be removed here'; end if; delete from public.admin_users where user_id=p_user_id; return found; end; $$;
create table if not exists public.fulfillment_orders (id uuid primary key default gen_random_uuid(),external_source text not null default 'manual',external_order_id text,order_number text,customer_name text,customer_email text,status text not null default 'pending' check(status in ('pending','ready','packing','fulfilled','cancelled')),raw_order jsonb not null default '{}'::jsonb,ordered_at timestamptz,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),unique(external_source,external_order_id));
create table if not exists public.fulfillment_order_items (id uuid primary key default gen_random_uuid(),order_id uuid not null references public.fulfillment_orders(id) on delete cascade,external_line_item_id text,sku text,product_name text not null,quantity integer not null default 1 check(quantity>0),physical_box_id uuid references public.physical_treasure_boxes(id),created_at timestamptz not null default now());
alter table public.fulfillment_orders enable row level security; alter table public.fulfillment_order_items enable row level security;
create policy "Admins view fulfillment orders" on public.fulfillment_orders for select to authenticated using(public.is_legacy_link_admin());
create policy "Admins view fulfillment items" on public.fulfillment_order_items for select to authenticated using(public.is_legacy_link_admin());
create or replace function public.admin_provision_physical_treasure_box(p_edition text default null) returns table(physical_box_id uuid,box_id text,activation_pin text,nfc_public_token uuid,nfc_path text) language plpgsql security definer set search_path='' as $$ declare v_id uuid:=gen_random_uuid(); v_serial text:=public.format_physical_treasure_box_serial(nextval('public.physical_treasure_box_serial_seq')); v_pin text:=public.generate_treasure_box_activation_pin(); v_nfc uuid:=gen_random_uuid(); begin if not public.is_legacy_link_admin() then raise exception 'Admin access required'; end if; insert into public.physical_treasure_boxes(id,serial_code,edition,claim_status,activation_pin_hash,activation_pin_last4,pin_generated_at,nfc_public_token,provisioned_at,setup_status) values(v_id,v_serial,p_edition,'unclaimed',crypt(v_pin,gen_salt('bf',10)),right(v_pin,4),now(),v_nfc,now(),'not_started'); return query select v_id,v_serial,v_pin,v_nfc,'/n/'||v_nfc::text; end; $$;
revoke all on function public.list_legacy_link_admins() from public; grant execute on function public.list_legacy_link_admins() to authenticated;
revoke all on function public.grant_legacy_link_admin(text,text) from public; grant execute on function public.grant_legacy_link_admin(text,text) to authenticated;
revoke all on function public.revoke_legacy_link_admin(uuid) from public; grant execute on function public.revoke_legacy_link_admin(uuid) to authenticated;
revoke all on function public.admin_provision_physical_treasure_box(text) from public; grant execute on function public.admin_provision_physical_treasure_box(text) to authenticated;
-- Production bootstrap: initial super-admin is seeded separately by deployment/admin operation, not by hard-coded user ID in source migration.
